import turtle
c = turtle.Pen()
c.fillcolor('yellow')
c.begin_fill()
c.circle(50)
c.end_fill()
c.fillcolor('red')
c.begin_fill()
c.circle(30)
c.end_fill()
c.fillcolor('blue')
c.begin_fill()
c.circle(20)
c.end_fill()
c.hideturtle()